#!/bin/bash
echo "Script for test of devy_for_ubuntu"
read -n1 -p "Do you want to start te test? [y,n]:" doit 
case $doit in  
  y|Y)  echo "\n"
	  ./devy_for_ubuntu <<<'1 2 4 1 0';; 
  n|N) echo bye;; 
  *) echo dont know ;; 
esac
